version: "3"

services:

  app:
    image: nginx
    deploy:
      restart_policy:
        condition: any
      #labels:
      #  SERVICE_5000_NAME: "registry"
      mode: replicated
      replicas: 2
      update_config:
        delay: 2s

  lb:
    image: n0r1skcom/ingress-controller
    entrypoint: /data/ingress-controller
    ports:
      - 23233:80
    environment:
      - INGRESS_STACK_SERVICE_DNS=tasks.ingress_app
      - INGRESS_STACK_SERVICE_PORT=80
      - INGRESS_STACK_SERVICE_TEMPLATE=/config/ingress-controller-config.tpl
      - INGRESS_STACK_SERVICE_CONFIGPATH=/etc/nginx/nginx.conf
      - INGRESS_STACK_SERVICE_STARTCOMMAND="nginx -g daemon off;"
      - INGRESS_STACK_SERVICE_RELOADCOMMAND="nginx -s reload"
    deploy:
      restart_policy:
        condition: any
      mode: replicated
      replicas: 1
      update_config:
        delay: 2s

networks:
  ingress-test:
    driver: overlay
